# Standards: 0.1
---
homebrew_user: detbo
homebrew_group: 1008259851

homebrew_taps:
  - webhippie/webhippie
  - webhippie/casks
  - homebrew/cask-drivers

homebrew_casks:
  - multipass
  - mumble
  - tunnelblick
  - skype-for-business
  - swiftdefaultappsprefpane
  - jabra-direct
  - macdown
  - yed
  - zoomus
  - battle-net

homebrew_packages:
  - autojump
  - bash
  - bash-completion
  - boilr
  - cfssl
  - coreutils
  - curl
  - direnv
  - dnsmasq
  - drone-cli
  - fd
  - fzf
  - ghi
  - ghq
  - gist
  - git
  - git-plus
  - gitlab-runner
  - gnu-getopt
  - gnu-sed
  - gnu-tar
  - gnupg
  - go
  - gomplate
  - gopass
  - govc
  - graphviz
  - grep
  - hcloud
  - htop
  - httpie
  - hub
  - hugo
  - ipcalc
  - irssi
  - jq
  - jsonnet
  - kubernetes-cli
  - m-cli
  - mcrcon
  - minio-mc
  - mysql
  - ncdu
  - netcat
  - nmap
  - node
  - pinentry-mac
  - pwgen
  - pygments
  - qemu
  - ripgrep
  - rsync
  - ruby
  - scw
  - shellcheck
  - snapcraft
  - socat
  - sqlite
  - stern
  - telnet
  - thefuck
  - the_platinum_searcher
  - tmux
  - tree
  - upx
  - vault
  - vim
  - visionmedia-watch
  - wget
  - wireguard-tools
  - xhyve
  - xz
  - yarn
  - yq
  - packer
  - terraform

...
